### ISSUE TITLE
申请api使用的时候提示错误

### ISSUE THREAD

**Issue by martjay** [Licoy/VoAPI#2]
{
  "error": {
    "message": "用户未拥有权限：请通过L站登陆，并等级>=1级便可使用 (request id: 20241011094540693947550TqSfh81v)",
    "type": "voapi_error"
  }
}

**Comment by martjay** [comment]
我不理解L站是什么网站跟你们的网站有什么关系？

**Comment by Licoy** [comment]
无关系，L站是https://linux.do，公益演示站为了避免滥用，所以做了一定的限制，不然机器人注册薅羊毛的太多了

**Comment by martjay** [comment]
> 无关系，L站是 https://linux.do ，公益演示站为了避免滥用，所以做了一定的限制，不然机器人注册薅羊毛的太多了

可是我怎么跟api网站关联上呢？

**Comment by martjay** [comment]
> 无关系，L站是 https://linux.do ，公益演示站为了避免滥用，所以做了一定的限制，不然机器人注册薅羊毛的太多了

仅支持邀请注册呢，你能给我发邀请注册链接不

**Comment by Licoy** [comment]
在网站登陆的时候，有个LinuxDO登陆，然后选择登陆即可

**Comment by martjay** [comment]
> 在网站登陆的时候，有个LinuxDO登陆，然后选择登陆即可

linux.do用google登录后提示注册需要邀请

**Comment by davidxzfei** [comment]
我是用github账号登录的，我的github账号是符合API调用要求的(至少1个公共Repo, 3个关注，账号年龄有好几年了。），为啥API调用的时候一直是返回401， 无效的令牌？

**Comment by Licoy** [comment]
目前已不需要，只需要使用qq数字邮箱注册即可

**Comment by davidxzfei** [comment]
@martjay 你一开始这个错误是咋出现的？我是申请了令牌后做测试，无论是用纯数字QQ邮箱还是合格的github账号，都说无效的令牌。
