### ISSUE TITLE
容器无法启动

### ISSUE THREAD

**Issue by lengxii** [Licoy/VoAPI#5]
[SYS] 2024/10/13 - 17:11:24 | VoAPI v0.0.59 started
[SYS] 2024/10/13 - 17:11:24 | SQL_DSN not set, using SQLite as database
[SYS] 2024/10/13 - 17:11:24 | database migration started
[SYS] 2024/10/13 - 17:11:24 | database migrated
[SYS] 2024/10/13 - 17:11:37 | VoAPI v0.0.59 started
[SYS] 2024/10/13 - 17:11:37 | SQL_DSN not set, using SQLite as database
[SYS] 2024/10/13 - 17:11:37 | database migration started
[SYS] 2024/10/13 - 17:11:37 | database migrated
[SYS] 2024/10/13 - 17:12:03 | VoAPI v0.0.59 started
[SYS] 2024/10/13 - 17:12:03 | SQL_DSN not set, using SQLite as database
[SYS] 2024/10/13 - 17:12:03 | database migration started
[SYS] 2024/10/13 - 17:12:03 | database migrated

打开网页报错 502

**Comment by Licoy** [comment]
sqlite不支持json类型字段的问题，晚点0.0.60中更新兼容，或使用mysql即可
